version: '2.1'

services:

  etl:
    build: .
    volumes:
      - .:/app
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.5.1'
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.routing.allocation.disk.threshold_enabled=true"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 30s
      retries: 3
