version: '2.1'

services:

  base: &base
    build: .
    volumes:
      - .:/app
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      AWS_REGION: 'ap-southeast-2'
      AWS_SERVICE: 'es'
      AWS_ES_SECRET_ACCESS_KEY_PROD:
      AWS_ES_KEY_ID_PROD:
      ATLAS_ZIP_TARGET: '/tmp/surrounding_suburbs.zip'
      ATLAS_CSV_TARGET: '/tmp'

  test:
    <<: *base
    environment:
      ELASTICSEARCH_BASE_URL: 'http://elasticsearch:9200/'
      ATLAS_ZIP_SOURCE: 'https://github.com/Kalimaha/flatmates-atlas-etl/blob/master/resources/surrounding_suburbs.zip?raw=true'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.5.1'
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      - 'xpack.security.enabled=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'cluster.routing.allocation.disk.threshold_enabled=true'
    ports:
      - 9200:9200
    healthcheck:
      test: ['CMD-SHELL', 'curl --silent --fail localhost:9200/_cluster/health || exit 1']
      interval: 15s
      timeout: 30s
      retries: 3
